version: '3.9'

services:

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on: 
      - mariadb
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/wordpress
    restart: unless-stopped

  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on: 
      - wordpress
    env_file: 
      - .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    restart: unless-stopped

volumes:

  db_data:
    driver: local
    name: db_data
    driver_opts: 
      #device: /Users/melanieyanez/Desktop/data/mariadb
      device: /home/myanez-p/data/mariadb
      type: none
      o: bind

  wp_data:
    driver: local
    name: wp_data
    driver_opts:
      #device: /Users/melanieyanez/Desktop/data/wordpress
      device: /home/myanez-p/data/wordpress
      type: none
      o: bind

networks:
  inception:
    driver: bridge